server:
  port: 8082
  servlet:
    context-path: /YouXian
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/youxian?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ZXZX78078
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true